import sys
import os

#3 lines of code to get the import from other files working
PACKAGE_PARENT = '..'
SCRIPT_DIR = os.path.dirname(os.path.realpath(os.path.join(os.getcwd(), os.path.expanduser(__file__))))
sys.path.append(os.path.normpath(os.path.join(SCRIPT_DIR, PACKAGE_PARENT)))

import Utils.fris_entities as fris_entities

def get_test_project():
    return fris_entities.Project("f5ee2534-30b8-4507-952b-f1e3bc4f5c57", "Resilience among Long-term Unemployed Youth", "Veerkracht bij langdurig werklozen jongere", \
    ["Unemployment","resilience","long-term unemployed youth","wellbeing"," job search"], [], \
        "&lt;p&gt;Werkloosheid is een belangrijk maatschappelijkÂ\\xa0probleem, met een negatieve impact op welvaart, welzijn en gezondheid. Deze studie onderzoekt de rolÂ\\xa0van veerkracht en de samenhangen ervan met welzijn en het vinden van werk bij jonge langdurig werklozen. Studie 1 exploreert de aanwezigheid van veerkracht en de correlaten ervan in een kwalitatieveÂ\\xa0studie. Studie 2 verruimt de vorige studie door veerkracht te onderzoeken in een cross-sectionele kwantitatieve studie, waarbij tevens de samenhang wordtÂ\\xa0onderzocht met de beoordeling (â€˜appraisalâ€™) van werkloosheid, coping strategieÃ«n, jobzoekgedrag enÂ\\xa0welzijn. Studie 3 onderzoekt de antecedenten en gevolgen van veerkracht na 6 maanden. De resultatenÂ\\xa0van deze studieÂ\\xa0zullen toelaten om wetenschappelijke theorieÃ«n over werkloosheid en veerkracht te verfijnen, en om interventies uit te werken om veerkracht te verhogen bij jonge langdurig werklozen, rekening houdend met de context en cultuur van hetÂ\\xa0land.&lt;/p&gt;",\
            "Unemployment is a major social problem that adversely impacts individualâ€™s welfare, healthÂ\\xa0and well-being. This study examines the role of resilienceÂ\\xa0and its associations with well-beingÂ\\xa0and behaviorsÂ\\xa0linked to re-employment, and focuses on a specific group at-risk: long-term unemployed youth. StudyÂ\\xa01 explores the existenceÂ\\xa0and correlates of resilience in a qualitative study. Study 2 extends the findings of study 1 by exploring resilience in a cross-sectional quantitativeÂ\\xa0sample, and analyses its association with appraisals of unemployment, coping strategies, job seeking and well-being. StudyÂ\\xa03 examines the antecedents and (behavioral and well-being) consequencesÂ\\xa0of resilience over time. TheÂ\\xa0results of thisÂ\\xa0project can be used to refine scientific theoriesÂ\\xa0on resilience and unemployment, and to develop interventions to increase resilienceÂ\\xa0among longÂ\\xa0term unemployed youth, that are aligned to the contextual and cultural framework of their country.&lt;/p&gt;")


def get_test_publication():
    return fris_entities.Publication("cfd4fd16-11f7-4d40-94e3-590b1337e633", "Hair as an alternative matrix to monitor human exposure to plasticizers - Development of a liquid chromatography - tandem mass spectrometry method","",[],[],\
        "The application and production of alternative plasticizers (APs) has been increasing in the last decade in replacement of conventional phthalates due to their toxicity. This calls for the development of non-invasive monitoring approaches to assess human exposure to APs. A method for the simultaneous measurement of exposure biomarkers of di(2-propylheptyl) phthalate (DPHP), di(isononyl)cyclohexane-1,2-dicarboxylate (DINCH), di(2-ethylhexyl) terephthalate (DEHTP) and di-2-ethylhexyl adipate (DEHA) in hair samples was developed and validated in this study. Prior to the analysis, the hair samples were washed in acetone and ultrapure water and pulverized to powder. Further, a solid-liquid and solid-phase extraction, followed by quantification using liquid chromatography - tandem mass spectrometry (LC-MS/MS) was performed. The method was validated in terms of recovery, matrix effects, carry-over, linearity, limits of quantification, within- and between-run precision and trueness. Satisfying results were obtained for all targeted compounds, except for mono(2-ethylhexyl) adipate (MEHA), which was monitored only qualitatively. The optimized method was implemented in a pilot biomonitoring study with hair samples from 9 healthy volunteers. Detection frequencies of seven metabolites ranged from 11% to 100%. Mono(2-ethylhexyl) terephthalate (MEHTP) and mono(2-ethyl-5-oxohexyl) adipate (oxo-MEHA) were found in all hair samples. More hydrophobic monoester metabolites were found to be incorporated in hair to a greater extent compared to their oxidized counterparts. Obtained results show that the developed method can detect AP metabolites in hair, supporting the use of this alternative matrix in human biomonitoring.","",\
            "https://doi.org/10.1016/j.jchromb.2018.09.031")

