import sys
import os

#3 lines of code to get the import form other files working
PACKAGE_PARENT = '..'
SCRIPT_DIR = os.path.dirname(os.path.realpath(os.path.join(os.getcwd(), os.path.expanduser(__file__))))
sys.path.append(os.path.normpath(os.path.join(SCRIPT_DIR, PACKAGE_PARENT)))

import Strategies.NetworkRelation.networkrelation as networkrelation

print(networkrelation.calculate_relations("The application and production of alternative plasticizers (APs) has been increasing in the last decade in replacement of conventional phthalates due to their toxicity. This calls for the development of non-invasive monitoring approaches to assess human exposure to APs. A method for the simultaneous measurement of exposure biomarkers of di(2-propylheptyl) phthalate (DPHP), di(isononyl)cyclohexane-1,2-dicarboxylate (DINCH), di(2-ethylhexyl) terephthalate (DEHTP) and di-2-ethylhexyl adipate (DEHA) in hair samples was developed and validated in this study. Prior to the analysis, the hair samples were washed in acetone and ultrapure water and pulverized to powder. Further, a solid-liquid and solid-phase extraction, followed by quantification using liquid chromatography - tandem mass spectrometry (LC-MS/MS) was performed. The method was validated in terms of recovery, matrix effects, carry-over, linearity, limits of quantification, within- and between-run.", 'en'))
print(networkrelation.calculate_relations("The application and production of alternative plasticizers (APs) has been increasing in the last decade in replacement of conventional phthalates due to their toxicity. This calls for the development of non-invasive monitoring approaches to assess human exposure to APs. A method for the simultaneous measurement of exposure biomarkers of di(2-propylheptyl) phthalate (DPHP), di(isononyl)cyclohexane-1,2-dicarboxylate (DINCH), di(2-ethylhexyl) terephthalate (DEHTP) and di-2-ethylhexyl adipate (DEHA) in hair samples was developed and validated in this study. Prior to the analysis, the hair samples were washed in acetone and ultrapure water and pulverized to powder. Further, a solid-liquid and solid-phase extraction, followed by quantification using liquid chromatography - tandem mass spectrometry (LC-MS/MS) was performed. The method was validated in terms of recovery, matrix effects, carry-over, linearity, limits of quantification, within- and between-run.", 'en'))